---
abstract: 'Run Data::Unixish function on the command-line'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-dux
requires:
  Data::Unixish: 1.31
  Module::List: 0
  Perinci::CmdLine: 0.93
  Perinci::Sub::Wrapper: 0.41
  Tie::Diamond: 0.03
  Tie::Simple: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-dux
  homepage: https://metacpan.org/release/App-dux
  repository: git://github.com/sharyanto/perl-App-dux.git
version: 1.37
